#!/usr/bin/env bash

if [ $# -eq 0 ]; then
	echo "Usage: $0 retroroller_1.0-1"
	exit 1
fi

sudo rm -rf $1
cp -rv dist $1
sudo chown -R root:root $1/
sudo chown -R odroid:odroid $1/home/odroid

sudo dpkg-deb --build $1
